package andersenlab.lesson.lesson11_1;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.List;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class CheckoutTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @BeforeAll
    public void setUp() {
        System.setProperty(
                "webdriver.chrome.driver", "src/main/resources/chromedriver.exe"
        );
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @AfterAll
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void checkout() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1035, 614));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".login_logo"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-backpack\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-onesie\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"remove-sauce-labs-onesie\"]")).click();
        driver.findElement(By.cssSelector(".shopping_cart_badge")).click();
        driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("asdf");
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("asdfff");
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("213123");
        driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".complete-text"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector("*[data-test=\"back-to-products\"]")).click();
        driver.close();
    }
}
