package andersenlab.lesson.lesson_13;// Generated by Selenium IDE

import andersenlab.lesson.lesson_12.TriangleArea;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.platform.commons.logging.Logger;
import org.junit.platform.commons.logging.LoggerFactory;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class OpenVerivoxProjectTest {
    private static Logger logger = LoggerFactory.getLogger(TriangleArea.class);

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public void setUp() {
        System.setProperty(
                "webdriver.chrome.driver", "src/main/resources/chromedriver.exe"
        );

        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS) ;
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterAll
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void openVerivoxProject() {
        driver.get("https://andersenlab.com/");
        driver.manage().window().setSize(new Dimension(1280, 680));
        driver.findElement(By.xpath("//a[contains(text(),'Projects')]")).click();
        driver.findElement(By.xpath("//section[@id='concepts-list']/div/div[2]/div/article[3]/a/div[2]/p")).click();

        assertThat(driver.findElement(By.xpath("//div[@id='gatsby-focus-wrapper']/main/section/div/div[2]/section/div/p")).getText(),
                is("The project is about modernizing Verivox's platform for collecting, aggregating," +
                        " and displaying multiple utility companies' rates to customers. Andersen's Front-end and" +
                        " Back-end teams are both working on the platform's functionality that will allow visitors to" +
                        " match rates through a comparison table and immediately choose the most suitable vendor" +
                        " corresponding to the specified parameters."));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".Banner-module--contentWrapper--S5Pd6"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".Header-module--topLineLayout--QWOUg"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".CaseIntro-module--title--1QRaI"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".ProjectConcept-module--visualConcept--0uP8J"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.xpath("/html/body/div[1]/div[1]/main/section[1]/div/div[1]/div/button[2]")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".review-module--header--i0kMM"));
            assert (elements.size() > 0);
        }
        assertThat(driver.findElement(By.cssSelector(".review-module--text--Alebt")).getText(), is("Our price comparison portal compares different private loans. At a certain moment, we realized our development team needed outsourced assistance. In Germany, it takes much time to adopt a new developer, usually over 3 months. Andersen offers quick onboarding so we can obtain a new developer within 2 weeks only. As we use a wide range of different technologies, including the Angular and Angular.js interfaces, in addition to the C # and PHP microservices, we selected 5 experienced coders from Andersen. They proved to be reliable and did write high-quality code. At the same time, they joined us in a prompt fashion. They are now a part of our SCRUM team and are considered internal developers."));
        driver.findElement(By.cssSelector(".GetConsultation-module--column--T1FhH > .title-module--title--xW-ym")).click();
        assertThat(driver.findElement(By.cssSelector(".GetConsultation-module--column--T1FhH > .title-module--title--xW-ym")).getText(), is("Contact us to discuss your IT project"));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".GetConsultation-module--column--T1FhH > .ProcessSteps-module--wrapper--PX2gj"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".ProjectGalleryCard-module--hoverWrapper--vtdPi"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".Footer-module--footer--LZE0a"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".Footer-module--contactUs--6nPqr > .Footer-module--title--bTyDR")).click();
        assertThat(driver.findElement(By.cssSelector(".Footer-module--contactUs--6nPqr > .Footer-module--title--bTyDR")).getText(), is("CONTACT US"));
        driver.close();
    }
}
