package andersenlab.lesson.lesson11_2;// Generated by Selenium IDE

import org.apache.commons.lang3.RandomStringUtils;
import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class DiaryTest {
    private String NAME;
    private String PASSWORD;
    private String EMAIL;

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public void setUp() {
        System.setProperty(
                "webdriver.chrome.driver", "src/main/resources/chromedriver.exe"
        );
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        String allowedChars = "abcdefghijklmnopqrstuvwxyz" + "1234567890" + "_-.";
        String allowedPasswordChars = "abcdefghijklmnopqrstuvwxyz" + "1234567890";
        NAME = RandomStringUtils.random(6, allowedChars);
        PASSWORD = RandomStringUtils.random(6, allowedPasswordChars);
        EMAIL = RandomStringUtils.random(6, allowedChars) + "@testdata.com";
    }

    @AfterAll
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    @Order(1)
    @Disabled("Changed web version")
    public void TestRegistration() {
        driver.get("https://diary.ru/");
        driver.manage().window().setSize(new Dimension(1035, 615));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys(NAME);
        {
            WebElement element = driver.findElement(By.cssSelector(".submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector(".submit")).click();
        vars.put("win4453", waitForWindow(2000));
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.switchTo().window(vars.get("win4453").toString());
        driver.findElement(By.id("signupform-email")).sendKeys(EMAIL);
        driver.findElement(By.id("signupform-password")).clear();
        driver.findElement(By.id("signupform-email")).sendKeys(PASSWORD);
        driver.findElement(By.cssSelector("small")).click();
        driver.findElement(By.id("signup_btn")).click();
        driver.findElement(By.cssSelector(".radio:nth-child(4) > label")).click();
        driver.findElement(By.name("new-blogs-button")).click();
        driver.findElement(By.id("drop_right_menu")).click();
        driver.close();
    }

    @Test
    @Order(2)
    public void Test_Login() {
        driver.get("https://diary.ru/user/login");
        driver.manage().window().setSize(new Dimension(1035, 615));
        driver.findElement(By.id("loginform-username")).click();
        driver.findElement(By.id("loginform-username")).sendKeys(NAME);
        driver.findElement(By.id("loginform-password")).click();
        driver.findElement(By.id("loginform-password")).sendKeys(PASSWORD);
        driver.switchTo().frame(0);
        driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
        driver.switchTo().defaultContent();
        driver.findElement(By.id("login_btn")).click();
    }

    @Test
    @Disabled("Changed web version")
    @Order(3)
    public void Test_Exit() {
        driver.get("https://diary.ru/");
        driver.manage().window().setSize(new Dimension(1035, 615));
        driver.findElement(By.id("drop_right_menu")).click();
        driver.findElement(By.linkText("Выход")).click();
        driver.close();
    }
}
